docs/CHANGELOG.md
pyproject.toml
src/microsweagent/__init__.py

- **Fix: micro-e extra invokation**
- **Fix: micro-extra invokation**

fix extra invokation

---

src/microsweagent/models/litellm_model.py

Gemini was returning None sometimes here

Fix: Make sure content is string

---

tests/conftest.py

Fix comment regarding threads lock

---

docs/quickstart.md

Doc: Clarify on 'full'

---

src/minisweagent/config/mini.yaml

Enh(config): Ask model to look at claude.md & friends

---

src/minisweagent/agents/interactive.py
src/minisweagent/run/mini.py
tests/agents/test_interactive.py
tests/run/test_cli_integration.py

Enh: mini --exit-immediately

---

.github/workflows/pylint.yaml
.github/workflows/pytest.yaml
.github/workflows/release.yaml

CI: Speedup testing with uv

---

.github/ISSUE_TEMPLATE/bug.yml
docs/usage/mini.md
docs/usage/mini_v.md
src/minisweagent/run/mini.py

Enh: Always save last trajectory

---

src/minisweagent/agents/default.py
src/minisweagent/agents/interactive.py

Reference: https://github.com/SWE-agent/mini-swe-agent/pull/328

[refactor] enable system prompt templating

---

src/minisweagent/agents/interactive_textual.py
src/minisweagent/config/mini.tcss

- **Enh(textual): Style keystrokes better**

enh style keystrokes

---

src/minisweagent/agents/interactive_textual.py

Enh(textual): help shortcut, ^y for yolo

---

src/minisweagent/config/mini.yaml

- **Change: Do not read Claude.md etc. by default**
- **Change(config): Do not read Claude.md by default**

do no tread claudemd by default

---

src/minisweagent/agents/default.py
src/minisweagent/config/default.yaml
src/minisweagent/config/extra/swebench.yaml
src/minisweagent/config/github_issue.yaml
src/minisweagent/config/mini.yaml
src/minisweagent/config/mini_no_temp.yaml
tests/agents/test_default.py
tests/agents/test_interactive.py
tests/agents/test_interactive_textual.py
tests/run/test_inspector.py

- **tmp**
- **Change: exit sequence; SWE-bench prompts**

Change: exit sequence; SWE-bench prompts

---

src/minisweagent/__init__.py
src/minisweagent/agents/default.py
src/minisweagent/agents/interactive_textual.py

Enh: Allow to add extra formatting kwargs in Agent.run()

---

src/minisweagent/agents/default.py

Enh: Persist task vars for template formatting

---

src/minisweagent/environments/docker.py
src/minisweagent/environments/singularity.py
src/minisweagent/run/extra/swebench.py
src/minisweagent/run/extra/swebench_single.py
src/minisweagent/run/utils/save.py
src/minisweagent/utils/log.py

Feat: Add minimal logging to environments & batch runs

---

docs/advanced/local_models.md

Doc: Improve local model support page

---

src/minisweagent/models/__init__.py
tests/models/test_init.py

Fix: config file model_name preference over env var

---

pyproject.toml

Deps: Remove upper cap on openai version

---

src/minisweagent/run/extra/swebench.py
src/minisweagent/run/github_issue.py

In rare cases, this might have caused environment/agent config to not be
properly set

Fix: setdefault instead of get

---

src/minisweagent/models/__init__.py
tests/models/test_init.py

Fix: get_model with deterministic model

---

src/minisweagent/agents/interactive_textual.py

Fix: mini -v attribute error upon save

---

docs/usage/swebench.md
src/minisweagent/run/extra/swebench.py

Feat: Support for SWE-bench startup command

---

src/minisweagent/models/litellm_model.py
src/minisweagent/models/openrouter_model.py

Fix: Response serialization error

---

docs/models/local_models.md

Doc: Fix api base syntax
